"""Tests for first-contact reliability bugs (portability on unconfigured machines).

Validates:
1. resolve_repo() uses workspace parameter as clone destination, not config's clone_base_path
2. Hook files generated by cap init use the thin-wrapper import pattern
3. _find_all_repos() discovers repos at any depth from 1 to 5
"""
import os
import sys
from pathlib import Path
from unittest.mock import patch, MagicMock

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from cap.lib.repo_resolver import resolve_repo, _find_local_repo, _validate_name
from cap.lib.sync_engine import _find_all_repos
from cap.cli.lifecycle import _generate_hook_scripts


# ── Fixtures ────────────────────────────────────────────────────────────────────


@pytest.fixture
def github_config():
    """Minimal GitHubConfig with org set but NO clone_base_path."""
    from cap.lib.config import GitHubConfig
    return GitHubConfig(
        org="test-org",
        clone_base_path="",  # NOT configured
        use_ssh=True,
        auto_clone_on_missing_dep=True,
        max_auto_clones_per_session=10,
        default_branch="main",
        clone_depth=1,
    )


@pytest.fixture
def github_config_with_base(tmp_path):
    """GitHubConfig with clone_base_path set."""
    from cap.lib.config import GitHubConfig
    return GitHubConfig(
        org="test-org",
        clone_base_path=str(tmp_path / "configured-base"),
        use_ssh=True,
        auto_clone_on_missing_dep=True,
        max_auto_clones_per_session=10,
        default_branch="main",
        clone_depth=1,
    )


# ── Bug 1: resolve_repo workspace parameter ──────────────────────────────────


class TestResolveRepoWorkspace:

    def test_uses_workspace_param_as_clone_base(self, tmp_path, github_config):
        """When workspace is provided, it should be used as clone destination."""
        workspace_dir = tmp_path / "my-workspace"
        workspace_dir.mkdir()

        # Create a repo at workspace_dir/my-repo/.git
        repo_dir = workspace_dir / "my-repo"
        repo_dir.mkdir()
        (repo_dir / ".git").mkdir()

        result = resolve_repo(
            "my-repo",
            config=github_config,
            workspace=str(workspace_dir),
        )

        assert result["status"] == "found_locally"
        assert result["path"] == str(repo_dir)

    def test_workspace_param_overrides_config_clone_base_path(self, tmp_path, github_config_with_base):
        """workspace param takes precedence over config.clone_base_path."""
        # Set up repo ONLY in workspace, not in config's base path
        workspace_dir = tmp_path / "workspace-override"
        workspace_dir.mkdir()
        repo_dir = workspace_dir / "override-repo"
        repo_dir.mkdir()
        (repo_dir / ".git").mkdir()

        # Config's base path exists but does NOT have the repo
        config_base = Path(github_config_with_base.clone_base_path)
        config_base.mkdir(parents=True)

        result = resolve_repo(
            "override-repo",
            config=github_config_with_base,
            workspace=str(workspace_dir),
        )

        assert result["status"] == "found_locally"
        assert str(workspace_dir) in result["path"]

    def test_falls_back_to_cwd_when_no_workspace_and_no_config(self, tmp_path, github_config):
        """When neither workspace nor clone_base_path provided, uses CWD."""
        # Create repo in tmp_path (which we'll set as CWD)
        repo_dir = tmp_path / "cwd-repo"
        repo_dir.mkdir()
        (repo_dir / ".git").mkdir()

        with patch("cap.lib.repo_resolver.Path.cwd", return_value=tmp_path):
            result = resolve_repo(
                "cwd-repo",
                config=github_config,
            )

        assert result["status"] == "found_locally"
        assert result["path"] == str(repo_dir)

    def test_no_error_when_clone_base_path_not_configured(self, tmp_path, github_config):
        """Should NOT raise an error when clone_base_path is empty string."""
        # The old code would return an error here; the fix falls back to CWD
        with patch("cap.lib.repo_resolver.Path.cwd", return_value=tmp_path):
            result = resolve_repo(
                "nonexistent-repo",
                config=github_config,
            )

        # Should reach the "not found remote" check (or not_found), NOT an error about config
        assert result["status"] != "error" or "clone_base_path" not in result.get("message", "")


# ── Bug 2: _find_all_repos bounded recursive discovery ───────────────────────


class TestFindAllRepos:

    def test_finds_repo_at_depth_1(self, tmp_path):
        """Repos directly under workspace root should be found."""
        repo = tmp_path / "repo-a"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "repo-a" in names

    def test_finds_repo_at_depth_2(self, tmp_path):
        """Repos at team/repo level should be found."""
        team = tmp_path / "team-x"
        team.mkdir()
        repo = team / "service-b"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "service-b" in names

    def test_finds_repo_at_depth_3(self, tmp_path):
        """Repos at org/team/repo level should be found."""
        org = tmp_path / "github"
        org.mkdir()
        team = org / "platform"
        team.mkdir()
        repo = team / "deep-repo"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "deep-repo" in names

    def test_finds_repo_at_depth_4(self, tmp_path):
        """Repos at depth 4 should be found (was broken before fix)."""
        level1 = tmp_path / "level1"
        level1.mkdir()
        level2 = level1 / "level2"
        level2.mkdir()
        level3 = level2 / "level3"
        level3.mkdir()
        repo = level3 / "deep-service"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "deep-service" in names

    def test_finds_repo_at_depth_5(self, tmp_path):
        """Repos at max depth 5 should be found."""
        current = tmp_path
        for level in ["a", "b", "c", "d"]:
            current = current / level
            current.mkdir()
        repo = current / "very-deep-repo"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path), max_depth=5)
        names = [name for name, _ in repos]
        assert "very-deep-repo" in names

    def test_does_not_descend_into_found_repo(self, tmp_path):
        """Once .git is found, should not look for nested repos inside."""
        outer = tmp_path / "outer-repo"
        outer.mkdir()
        (outer / ".git").mkdir()

        # Nested repo inside outer (monorepo pattern — should NOT be discovered)
        inner = outer / "packages" / "inner-repo"
        inner.mkdir(parents=True)
        (inner / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "outer-repo" in names
        assert "inner-repo" not in names

    def test_skips_node_modules(self, tmp_path):
        """node_modules directories should be skipped."""
        nm = tmp_path / "node_modules"
        nm.mkdir()
        repo = nm / "some-pkg"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "some-pkg" not in names

    def test_skips_venv(self, tmp_path):
        """.venv directories should be skipped."""
        venv = tmp_path / ".venv"
        venv.mkdir()
        repo = venv / "lib-repo"
        repo.mkdir()
        (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "lib-repo" not in names

    def test_respects_max_repos_limit(self, tmp_path):
        """Should stop early once max_repos reached."""
        for i in range(10):
            repo = tmp_path / f"repo-{i}"
            repo.mkdir()
            (repo / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path), max_repos=5)
        assert len(repos) == 5

    def test_mixed_depths(self, tmp_path):
        """Should find repos at multiple different depths simultaneously."""
        # Depth 1
        r1 = tmp_path / "shallow"
        r1.mkdir()
        (r1 / ".git").mkdir()

        # Depth 3
        d1 = tmp_path / "org"
        d1.mkdir()
        d2 = d1 / "team"
        d2.mkdir()
        r3 = d2 / "deep"
        r3.mkdir()
        (r3 / ".git").mkdir()

        repos = _find_all_repos(str(tmp_path))
        names = [name for name, _ in repos]
        assert "shallow" in names
        assert "deep" in names


# ── Bug 3: Thin-wrapper hook generation ──────────────────────────────────────


class TestHookGeneration:

    def test_generates_thin_wrapper_pretool(self, tmp_path):
        """pretool.py should use import wrapper pattern."""
        claude_dir = tmp_path / ".claude"
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        _generate_hook_scripts(claude_dir, data_dir)

        pretool = claude_dir / "pretool.py"
        assert pretool.exists()
        content = pretool.read_text()
        assert "from cap.hooks.pretool import main" in content
        assert "sys.exit(main()" in content

    def test_generates_thin_wrapper_posttool(self, tmp_path):
        """posttool.py should use import wrapper pattern."""
        claude_dir = tmp_path / ".claude"
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        _generate_hook_scripts(claude_dir, data_dir)

        posttool = claude_dir / "posttool.py"
        assert posttool.exists()
        content = posttool.read_text()
        assert "from cap.hooks.posttool import main" in content
        assert "sys.exit(main()" in content

    def test_wrapper_has_importerror_fallback(self, tmp_path):
        """Wrappers should gracefully handle ImportError (CAP not installed)."""
        claude_dir = tmp_path / ".claude"
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        _generate_hook_scripts(claude_dir, data_dir)

        for hook_name in ("pretool.py", "posttool.py"):
            content = (claude_dir / hook_name).read_text()
            assert "except ImportError:" in content
            assert "pass  # CAP not installed, no-op" in content

    def test_wrapper_does_not_contain_inline_db_logic(self, tmp_path):
        """Wrappers should NOT contain sqlite3, DB_PATH, or inline logic."""
        claude_dir = tmp_path / ".claude"
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        _generate_hook_scripts(claude_dir, data_dir)

        for hook_name in ("pretool.py", "posttool.py"):
            content = (claude_dir / hook_name).read_text()
            assert "sqlite3" not in content
            assert "DB_PATH" not in content
            assert "conn = " not in content

    def test_overwrites_stale_inline_hooks(self, tmp_path):
        """If existing hook has inline logic (no import wrapper), it should be overwritten."""
        claude_dir = tmp_path / ".claude"
        claude_dir.mkdir(parents=True)
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        # Write a stale inline hook
        stale_content = '''#!/usr/bin/env python3
import sqlite3
import sys
DB_PATH = "/some/path/platform.db"
def main():
    conn = sqlite3.connect(DB_PATH)
    # inline logic here
    pass
if __name__ == "__main__":
    main()
'''
        (claude_dir / "pretool.py").write_text(stale_content)
        (claude_dir / "posttool.py").write_text(stale_content)

        result = _generate_hook_scripts(claude_dir, data_dir)

        assert result is True  # Should have updated
        content = (claude_dir / "pretool.py").read_text()
        assert "from cap.hooks.pretool import main" in content
        assert "sqlite3" not in content

    def test_does_not_overwrite_correct_wrapper(self, tmp_path):
        """If hook already has the correct thin wrapper, don't rewrite."""
        claude_dir = tmp_path / ".claude"
        claude_dir.mkdir(parents=True)
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        # First generate
        _generate_hook_scripts(claude_dir, data_dir)

        # Record mtime
        import time
        time.sleep(0.01)
        mtime_before = (claude_dir / "pretool.py").stat().st_mtime

        # Generate again — should skip
        time.sleep(0.01)
        result = _generate_hook_scripts(claude_dir, data_dir)

        assert result is False  # Nothing changed
        mtime_after = (claude_dir / "pretool.py").stat().st_mtime
        assert mtime_before == mtime_after

    def test_hook_is_executable(self, tmp_path):
        """Generated hooks should have executable permissions."""
        claude_dir = tmp_path / ".claude"
        data_dir = tmp_path / "data"
        data_dir.mkdir()

        _generate_hook_scripts(claude_dir, data_dir)

        for hook_name in ("pretool.py", "posttool.py"):
            hook_path = claude_dir / hook_name
            mode = hook_path.stat().st_mode
            assert mode & 0o111, f"{hook_name} is not executable"
