"""
CAP Configuration Manager — Parse ~/.cap/config.toml, workspace config.

Provides:
- Config dataclass with typed fields and defaults
- load(path) -> Config
- save(config, path) -> None
"""

import os
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import Optional

try:
    import tomllib  # Python 3.11+
except ModuleNotFoundError:
    try:
        import tomli as tomllib  # Fallback for Python 3.10
    except ModuleNotFoundError:
        tomllib = None

DEFAULT_CONFIG_PATH = os.path.expanduser("~/.cap/config.toml")


@dataclass
class Config:
    """CAP configuration with typed fields and defaults."""

    # Budget & limits
    daily_budget_usd: float = 5.0
    disk_budget_mb: int = 256
    enforcement_threshold: int = 3
    passthrough_ttl: int = 300
    passthrough_max_per_hour: int = 3

    # Database
    db_path: str = os.path.expanduser("~/.cap/cap.db")

    # Memory
    working_memory_tokens: int = 15_000
    eviction_score_threshold: float = 0.15
    stale_days: int = 90
    delete_days: int = 365
    delete_min_accesses: int = 3

    # Sync
    staleness_ttl: int = 300
    hash_check_interval: int = 300

    # Agent timeouts (seconds)
    agent_timeouts: dict = field(default_factory=lambda: {
        "dev": 300,
        "devops": 300,
        "security": 180,
        "sre": 180,
        "test": 240,
        "optimization": 240,
        "docs": 120,
        "cicd": 180,
        "aws-architect": 240,
        "code-review": 120,
        "data": 240,
        "frontend": 240,
    })

    # Model pricing per 1M tokens
    model_pricing: dict = field(default_factory=lambda: {
        "opus": {"input": 15.00, "output": 75.00},
        "sonnet": {"input": 3.00, "output": 15.00},
        "haiku": {"input": 0.25, "output": 1.25},
    })

    # Reliability
    circuit_breaker_failure_threshold: int = 3
    circuit_breaker_window_seconds: int = 300
    circuit_breaker_cooldown_seconds: int = 120
    cascade_window_seconds: int = 10
    cascade_threshold: int = 3

    def get(self, key: str, default=None):
        """Dict-like access for backward compatibility."""
        return getattr(self, key, default)


def load(path: str = None) -> Config:
    """
    Load configuration from TOML file.

    Falls back to defaults if file does not exist or tomllib is unavailable.

    Args:
        path: Path to config.toml. Defaults to ~/.cap/config.toml

    Returns:
        Config dataclass with values from file merged over defaults.
    """
    if path is None:
        path = DEFAULT_CONFIG_PATH

    config = Config()

    if not os.path.exists(path):
        return config

    if tomllib is None:
        # Cannot parse TOML without library, return defaults
        return config

    try:
        with open(path, "rb") as f:
            data = tomllib.load(f)
    except (OSError, ValueError):
        return config

    # Merge top-level scalar fields
    for key in (
        "daily_budget_usd", "disk_budget_mb", "enforcement_threshold",
        "passthrough_ttl", "passthrough_max_per_hour", "db_path",
        "working_memory_tokens", "eviction_score_threshold",
        "stale_days", "delete_days", "delete_min_accesses",
        "staleness_ttl", "hash_check_interval",
        "circuit_breaker_failure_threshold", "circuit_breaker_window_seconds",
        "circuit_breaker_cooldown_seconds", "cascade_window_seconds",
        "cascade_threshold",
    ):
        if key in data:
            setattr(config, key, data[key])

    # Merge dict fields (agent_timeouts, model_pricing)
    if "agent_timeouts" in data and isinstance(data["agent_timeouts"], dict):
        config.agent_timeouts.update(data["agent_timeouts"])

    if "model_pricing" in data and isinstance(data["model_pricing"], dict):
        config.model_pricing.update(data["model_pricing"])

    return config


def save(config: Config, path: str = None) -> None:
    """
    Save configuration to TOML file.

    Args:
        config: Config dataclass to save
        path: Path to write. Defaults to ~/.cap/config.toml
    """
    if path is None:
        path = DEFAULT_CONFIG_PATH

    # Ensure directory exists
    os.makedirs(os.path.dirname(path), exist_ok=True)

    lines = []
    lines.append("# CAP Configuration")
    lines.append("# Generated by cap init. Edit as needed.")
    lines.append("")

    # Scalar fields
    lines.append(f"daily_budget_usd = {config.daily_budget_usd}")
    lines.append(f"disk_budget_mb = {config.disk_budget_mb}")
    lines.append(f"enforcement_threshold = {config.enforcement_threshold}")
    lines.append(f"passthrough_ttl = {config.passthrough_ttl}")
    lines.append(f"passthrough_max_per_hour = {config.passthrough_max_per_hour}")
    lines.append(f'db_path = "{config.db_path}"')
    lines.append(f"working_memory_tokens = {config.working_memory_tokens}")
    lines.append(f"eviction_score_threshold = {config.eviction_score_threshold}")
    lines.append(f"stale_days = {config.stale_days}")
    lines.append(f"delete_days = {config.delete_days}")
    lines.append(f"delete_min_accesses = {config.delete_min_accesses}")
    lines.append(f"staleness_ttl = {config.staleness_ttl}")
    lines.append(f"hash_check_interval = {config.hash_check_interval}")
    lines.append(f"circuit_breaker_failure_threshold = {config.circuit_breaker_failure_threshold}")
    lines.append(f"circuit_breaker_window_seconds = {config.circuit_breaker_window_seconds}")
    lines.append(f"circuit_breaker_cooldown_seconds = {config.circuit_breaker_cooldown_seconds}")
    lines.append(f"cascade_window_seconds = {config.cascade_window_seconds}")
    lines.append(f"cascade_threshold = {config.cascade_threshold}")
    lines.append("")

    # Agent timeouts
    lines.append("[agent_timeouts]")
    for agent, timeout in config.agent_timeouts.items():
        lines.append(f'"{agent}" = {timeout}')
    lines.append("")

    # Model pricing
    lines.append("[model_pricing]")
    lines.append("[model_pricing.opus]")
    lines.append(f"input = {config.model_pricing['opus']['input']}")
    lines.append(f"output = {config.model_pricing['opus']['output']}")
    lines.append("[model_pricing.sonnet]")
    lines.append(f"input = {config.model_pricing['sonnet']['input']}")
    lines.append(f"output = {config.model_pricing['sonnet']['output']}")
    lines.append("[model_pricing.haiku]")
    lines.append(f"input = {config.model_pricing['haiku']['input']}")
    lines.append(f"output = {config.model_pricing['haiku']['output']}")
    lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))
